name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: translation-menu/menu@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'This looks like an issue! Repo: ${{ secrets.GITHUB_TOKEN }}'
        pr-message: 'This looks like a PR! ${{ secrets.GITHUB_TOKEN }}'
